version: '3.7'

services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=nc_passwd
      - POSTGRES_USER=nc_user
    volumes:
      - db:/var/lib/postgresql/data

  proxy:
    image: nginx:1.17-alpine
    ports:
      - 80:80
      - 443:443
    depends_on:
      - nextcloud 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - cert_letsencrypt:/letsencrypt:ro
      - nextcloud:/var/www/html:ro

  nextcloud:
    image: nextcloud:17-fpm-alpine
    depends_on:
      - db
    volumes:
      - nextcloud:/var/www/html
      - apps:/var/www/html/custom_apps
      - config:/var/www/html/config
      - data:/var/www/html/data

    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=nc_passwd
      - POSTGRES_USER=nc_user
      - POSTGRES_DB=nextcloud

volumes:
  db:
  nextcloud:
  cert_letsencrypt:
          external: true
  apps:
  config:
  data:
