version: '3.7'

services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - db:/var/lib/postgresql/data

  proxy:
    image: nginx:1.17-alpine
    ports:
      - 8080:80
    depends_on:
      - nextcloud 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nextcloud:/var/www/html:ro

  nextcloud:
    image: nextcloud:15-fpm-alpine
    depends_on:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nextcloud

volumes:
  db:
  nextcloud:

